version: "2"
run:
  issues-exit-code: 1
  relative-path-mode: gomod
  tests: true
  go: "1.24"
linters:
  enable:
    - copyloopvar
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
output:
  formats:
    json:
      path: stdout
  show-stats: false
